create table if not exists public.automata_state (
  name text primary key,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.automata_state enable row level security;
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.automata_state to service_role;

-- La service role usada solo por el servidor omite RLS. No expongas esa clave al navegador.

create table if not exists public.automata_orders (
  id text primary key,
  public_token_hash text not null unique,
  product_code text not null,
  customer_name text not null,
  customer_email text not null,
  topic text not null,
  context text not null default '',
  objective text not null,
  status text not null check (status in (
    'awaiting_payment', 'paid', 'processing', 'delivered', 'failed', 'payment_reversed'
  )),
  currency text not null check (currency = 'CLP'),
  amount integer not null check (amount >= 1000),
  checkout_url text,
  provider_preference_id text,
  provider_payment_id text unique,
  payment_status text not null default 'not_started',
  report_markdown text,
  generation_usage jsonb,
  attempts integer not null default 0 check (attempts between 0 and 10),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  processing_at timestamptz,
  delivered_at timestamptz
);

create index if not exists automata_orders_status_paid_at_idx
  on public.automata_orders (status, paid_at);
create index if not exists automata_orders_created_at_idx
  on public.automata_orders (created_at desc);

alter table public.automata_orders enable row level security;
grant select, insert, update, delete on table public.automata_orders to service_role;

create table if not exists public.automata_ledger (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  order_id text references public.automata_orders(id) on delete set null,
  kind text not null check (kind in ('revenue', 'reversal', 'generation')),
  amount numeric(14, 4) not null,
  currency text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists automata_ledger_created_at_idx
  on public.automata_ledger (created_at desc);

alter table public.automata_ledger enable row level security;
grant select, insert, update, delete on table public.automata_ledger to service_role;
grant usage, select on sequence public.automata_ledger_id_seq to service_role;
